### ISSUE TITLE
Possible optimization

### ISSUE THREAD

**Issue by madanyang** [bmwiedemann/bench-http#1]
Hi,

First of all a very nice tool congrats, just an observation why not start with the geo location in the beginning to limit the mirrors to be checked to the ones that make sense, ie when in Germany why would I want to use a mirror from the other part of the world.

**Comment by bmwiedemann** [comment]
Hi. I thought about this optimization, but there have been reports from people in Africa that had better experience with German mirrors, so YMMV.

OTOH, there exists now [one optimization](https://github.com/bmwiedemann/bench-http/commit/be712df1b2f079814ec67ab62497ac2902280e93) that will auto-limit scanning to the closest 15+ mirrors as measured by RTT.

With that, my scan time went down to 45s.

**Comment by bmwiedemann** [comment]
Can you try the new `benchlist.pl` and test if the scan is fast enough for you?

**Comment by madanyang** [comment]
Hi,

Thanks for the new version yes scan is faster now.

**Comment by madanyang** [comment]
I thinki we can close this one, unless you feel otherwise
