### ISSUE TITLE
Can't run benchlist.pl

### ISSUE THREAD

**Issue by masroof-maindak** [bmwiedemann/bench-http#4]
```
Can't locate WWW/Curl/Easy.pm in @INC (you may need to install the WWW::Curl::Easy module) (@INC entries checked: /usr/lib/perl5/site_perl/5.38.0/x86_64-linux-thread-multi /usr/lib/perl5/site_perl/5.38.0 /usr/lib/perl5/vendor_perl/5.38.0/x86_64-linux-thread-multi /usr/lib/perl5/vendor_perl/5.38.0 /usr/lib/perl5/5.38.0/x86_64-linux-thread-multi /usr/lib/perl5/5.38.0 /usr/lib/perl5/site_perl) at ./benchlist.pl line 7.
BEGIN failed--compilation aborted at ./benchlist.pl line 7.
```
This is the error output I'm getting. I made sure to install the deps. Any help would be much appreciated.

**Comment by bmwiedemann** [comment]
Thanks for the report, I pushed an update with more instructions.

**Comment by masroof-maindak** [comment]
Hello, sorry for bothering you again, but you could tell me what repo the new package is in? I've had no luck trying to install it w/ Zypper and couldn't find it online. I also checked Yast Software Management in case you had made a typo but it wasn't there either.

![image](https://github.com/bmwiedemann/bench-http/assets/62666332/38fa61ff-40c4-45e2-92ba-542cc02b915c)

**Comment by bmwiedemann** [comment]
You need to add the right repo from https://download.opensuse.org/repositories/devel:/languages:/perl/ (as added to the Readme now)

**Comment by bmwiedemann** [comment]
note: I updated the code+docs to use perl-Net-Curl instead.
